#!/usr/bin/env bash
set -euo pipefail
REPO="${1:?usage: create_labels.sh OWNER/ainol-octo-server-product-hub}"
create_label() {
  local name="$1" color="$2" desc="$3"
  gh label create "$name" --repo "$REPO" --color "$color" --description "$desc" 2>/dev/null || \
  gh label edit "$name" --repo "$REPO" --color "$color" --description "$desc"
}
create_label 'type/question' '0969DA' '产品或代码问题'
create_label 'type/bug' 'D73A4A' 'Bug 反馈'
create_label 'type/feature' 'A2EEEF' '新需求'
create_label 'type/docs' '0075CA' '文档缺失或说明不清'
create_label 'type/prd' '5319E7' 'PRD 任务'
create_label 'type/review' 'BFD4F2' 'Review 任务'
create_label 'priority/P0' 'B60205' '安全、凭证、登录不可用、Bot/Agent 断联、考试核心链路阻塞'
create_label 'priority/P1' 'D93F0B' '核心功能异常或重要需求'
create_label 'priority/P2' 'FBCA04' '常规缺陷或普通增强'
create_label 'priority/P3' 'C5DEF5' '低优先级建议、体验优化'
create_label 'status/inbox' 'EDEDED' '新进入，未分诊'
create_label 'status/triaged' 'C2E0C6' '已分诊'
create_label 'status/needs-clarification' 'FEF2C0' '信息不足，需要澄清'
create_label 'status/prd-drafting' 'D4C5F9' 'PRD 草稿中'
create_label 'status/prd-review' 'BFDADC' '等待 Review'
create_label 'status/rework' 'F9D0C4' 'Review 打回，需修改'
create_label 'status/accepted' '0E8A16' '已接受处理'
create_label 'status/blocked' 'B60205' '被阻塞'
create_label 'status/wontfix' 'FFFFFF' '决定不做'
create_label 'status/done' '0E8A16' '已完成'
create_label 'status/duplicate' 'CFD3D7' '重复'
create_label 'status/invalid' 'E4E669' '无效'
create_label 'area/auth' '1D76DB' '认证与身份'
create_label 'area/rbac' '1D76DB' '鉴权模型 / RBAC / ACL'
create_label 'area/config' '1D76DB' '配置'
create_label 'area/modules' '1D76DB' '业务模块清单'
create_label 'area/api-error' '1D76DB' 'API 与错误约定'
create_label 'area/im' '1D76DB' 'IM 控制面'
create_label 'area/bot-agent' '1D76DB' 'Bot 与 Agent'
create_label 'area/storage' '1D76DB' '存储与外部依赖'
create_label 'area/build-release' '1D76DB' '构建与发布'
create_label 'area/unknown' 'D0D7DE' '暂不能判断'
create_label 'pm/needs-prd' 'FBCA04' '需要补 PRD'
create_label 'pm/prd-ready' '0E8A16' 'PRD 已准备好'
create_label 'pm/review-requested' '5319E7' '已请求 Review'
create_label 'pm/review-approved' '0E8A16' 'Review 通过'
create_label 'pm/review-rejected' 'D73A4A' 'Review 打回'
create_label 'pm/human-needed' 'B60205' '需要人工接管'
create_label 'source/exam-group' 'C5DEF5' '考试群输入'
create_label 'source/cron-detected' 'C5DEF5' 'cron 扫描发现'
create_label 'source/manual-triage' 'C5DEF5' '人工分诊'
create_label 'source/evaluation' 'C5DEF5' '评测集输入'
create_label 'source/agent' 'C5DEF5' 'Agent 生成'
create_label 'risk/security' 'B60205' '安全风险'
create_label 'risk/privacy' 'B60205' '隐私风险'
create_label 'risk/ambiguous' 'FBCA04' '信息模糊'
create_label 'risk/evidence-missing' 'FBCA04' '证据不足'
create_label 'risk/citation-invalid' 'D73A4A' '引用失效'
create_label 'risk/token-leak' 'B60205' '凭证泄露风险'
